bike_project:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      dataset: montpellier_bikes
      threads: 4
      keyfile: ./dbt-service-account.json
      location: EU 